### ISSUE TITLE
[FEAT] 채팅방 생성/수정 관련 API 생성

### ISSUE THREAD

**Issue by cjaehyuk4zed** [ajou-JSL/Backend-Multi-Module#10]
## 🖥️ Descriptions
 - 채팅방 생성/수정 관련 API 생성
 -  chatappmodule을 클라우드 서버에 성공적으로 이식하면 작업 시작할 예정이다.
 - 채팅'방' 정보는 MongoDB가 아니라 MySQL에 저장되기 때문이다.

## ✅ Todo
- [x] R2DBC드라이버로 MySQL 통신 확인
- [x] 채팅방 생성 API 
- [x] 채팅방 수정 API
- [x] API 테스트
- [x] 프론트엔드와 통합 테스트

## ☁️ ETC
 - chatappmodule을 클라우드 서버에 성공적으로 이식하면 작업 시작할 예정이다.
 - 채팅'방' 정보는 MongoDB가 아니라 MySQL에 저장되기 때문이다.
