### ISSUE TITLE
ex) [FEAT] QR Code 및 공연장 홍보 페이지 생성

### ISSUE THREAD

**Issue by cjaehyuk4zed** [ajou-JSL/Backend-Multi-Module#24]
## 🖥️ Descriptions
 - 공연장 홍보 페이지 생성
 - 홍보 페이지에 대한 QR Code 생성
 - 홍보 페이지는, "공연 게시글" 작성 시 자동으로 함께 생성되도록 설계

## ✅ Todo
- [x] 홍보 페이지 로직 구현
- [x] Thymeleaf 홍보 페이지 생성
- [x] 홍보 페이지에 정보 변수 삽입
- [x] API 테스트

## ☁️ ETC
 - 내용을 적어주세요
