### ISSUE TITLE
ex) [FEAT] 관리자 대시보드 세부 기능 구현

### ISSUE THREAD

**Issue by cjaehyuk4zed** [ajou-JSL/Backend-Multi-Module#25]
## 🖥️ Descriptions
 - 관리자 대시보드의 세부 기능 구현
 - 채팅방 목록 관리
 - 사용자 신고 관리
 - 게시글 신고 관리
 - 단체 신고 관리
 - 연습실 & 공연장 정보 관리
 - 각 페이지에 대하여 Thymeleaf 변수 삽입 및 수정 테스트

## ✅ Todo
- [x] 채팅방 목록 관리 페이지 생성
- [x] 채팅방 목록 관리 CRUD 구현
-----
- [x] 사용자 신고 관리 페이지 생성
- [x] 사용자 신고 관리 CRUD 구현
-----
- [x] 게시글 신고 관리 페이지 생성
- [x] 게시글 신고 관리 CRUD 구현
-----
- [x] 단체 신고 관리 페이지 생성
- [x] 단체 신고 관리 CRUD 구현
-----
- [x] 연습실 정보 관리 페이지 생성
- [x] 연습실 정보 관리 CRUD 구현
-----
- [x] 공연장 정보 관리 페이지 생성
- [x] 공연장 정보 관리 CRUD 구현
-----
- [x] API 테스트
- [x] 검색 필터 정확도, 정밀도, 속도 테스트

## ☁️ ETC
 - 내용을 적어주세요
