### ISSUE TITLE
[FEAT] 회원, 게시글 등 필터링 조회 기능 확장

### ISSUE THREAD

**Issue by 2eungwoo** [ajou-JSL/Backend-Multi-Module#26]
## 🖥️ Descriptions
 - 회원 프로필 정보 기반 필터링 조회 

## ✅ Todo
- [x] 회원에 장르 필드 추가, 회원가입,수정 변경
- [x] 게시글에 장르 필드 추가, 게시글 작성,수정 변경
- [x] 공연게시글에 장르 필드 추가, 생성,수정 변경
- [x] 회원 프로필 리스트 필터링 조회
- [x] 게시글 리스트 필터링 조회

## ☁️ ETC
 - 내용을 적어주세요
