### ISSUE TITLE
[FEAT] 공연게시판 조회 API에 단체이름 추가 요청

### ISSUE THREAD

**Issue by soseongha** [ajou-JSL/Backend-Multi-Module#28]
## 🖥️ Descriptions
 - 공연게시판 조회하는 API들 모두에서 response에 단체이름을 추가 부탁드립니다.
 - 필드 이름은 "teamName"으로 부탁드립니다.
 - 또한, 더불어서 공연게시글 수정 및 삭제 API도 추가 부탁드립니다.

## ✅ Todo
- [x] 공연게시판 조회 API들 response에 단체 이름 추가
- [x] 공연게시글 수정 API 추가
- [x] 공연게시글 삭제 API 추가
- [x] price 타입 string -> int 변경
