### ISSUE TITLE
ex) [FEAT] 신고 기능 구현

### ISSUE THREAD

**Issue by cjaehyuk4zed** [ajou-JSL/Backend-Multi-Module#29]
## 🖥️ Descriptions
 - 사용자 신고
 - 음악단체 신고
 - 게시글 신고

## ✅ Todo
- [x] #45
- [x] 사용자 신고 조회
- [x] 사용자 신고 답변
- [x] 사용자 비활성화 (밴)
- [x] 음악단체 신고
- [x] 음악단체 신고 조회
- [x] 음악단체 신고 답변
- [x] 게시글 신고
- [x] 게시글 신고 조회
- [x] 게시글 신고 답변
- [x] 게시글 삭제
- [x] API 테스트

## ☁️ ETC
 - 신고 자체에 대한 API 기능 구현
 - 신고 수정, 답변 등은 관리자 기능에서 구현할 것임
