### ISSUE TITLE
[FEAT] 필터링 검색 기능

### ISSUE THREAD

**Issue by 2eungwoo** [ajou-JSL/Backend-Multi-Module#32]
## 🖥️ Descriptions
 - 내용을 적어주세요

## ✅ Todo
- [x] 일반게시글 : 조회수순조회, 최신순조회, 댓글순조회, 좋아요순조회, 검색조회
- [x] 공연게시글 : 최신순조회, 검색조회(공연이름+공연설명), 좋아요순, 조회수순, 장르별, 지역별, 공연시작날짜, 공연마감날짜
- [x] 팀 : 랭킹순조회, 멤버수순조회, 검색조회(팀이름,팀설명), 장르별
- [ ] 연습실 : 이름, 주소, Latitude/Longitude(?), 가격, 최대인원수, Type, 보면대개수 
                     [피아노, 앰프, 스피커, 마이크, 드럼] 여부
- [ ] 공연장 : 이름, 주소, Latitude/Longitude(?), 가격, 무대크기, 최대관객수, 보면대개수
                     [피아노, 앰프, 스피커, 마이크, 드럼] 여부

## ☁️ ETC
 - 내용을 적어주세요
