### ISSUE TITLE
ex) [FEAT] UI 정리

### ISSUE THREAD

**Issue by cjaehyuk4zed** [ajou-JSL/Backend-Multi-Module#34]
## 🖥️ Descriptions
 - UI 페이지 정리
 - null 값에 대한 display값 처리
 - 영어 단어들 상황에 알맞게 한국어로 변경 (또는 영어 유지)

## ✅ Todo 
- [ ] "채팅방 관리"에서 teamId = null 이면 "개인채팅"으로 표기
- [ ] 관리자 페이지에서 일부 영어를 알맞게 한국어로 표기
- [ ] QR 팜플렛에서 썸네일 이미지 max-width 늘리기

## ☁️ ETC
 - 생각나는 거 있으면 바로바로 추가하기
