### ISSUE TITLE
ex) [FEAT] Github Action 배포 자동화

### ISSUE THREAD

**Issue by cjaehyuk4zed** [ajou-JSL/Backend-Multi-Module#41]
## 🖥️ Descriptions
 - Github Action 배포 자동화

## ✅ Todo
- [x] Github Action 공부
- [x] 자동화 스크립트 작성
- [x] 승우님과 함께 테스트

## ☁️ ETC
 - 내용을 적어주세요
