### ISSUE TITLE
[FEAT] 회원 탈퇴 추가

### ISSUE THREAD

**Issue by 2eungwoo** [ajou-JSL/Backend-Multi-Module#44]
## 🖥️ Descriptions
 - 회원 탈퇴 => Boolean active_status 필드 사용 

## ✅ Todo
- [x] 회원 탈퇴 API, 재가입 API 추가
- [x] 회원 탈퇴 시 로그인 실패 처리
- [x] 회원 탈퇴 시 회원가입 때 중복검사 처리
- [x] 테스트코드 추가 및 수정

## ☁️ ETC
 - 내용을 적어주세요
