### ISSUE TITLE
[FEAT] 라이프사이클(moum) 기능

### ISSUE THREAD

**Issue by 2eungwoo** [ajou-JSL/Backend-Multi-Module#7]
## 🖥️ Descriptions
 - 라이프사이클 관리 기능 
 
## ✅ Todo
- [x] 생성, 단건조회, 목록조회
- [x] 수정, 삭제
- [x] 이력추가
- [x] 마감, 되살리기 (상태변경)
   - [x] 마감,되살리기 -> 이력 적용
- [x] 기타 상태값 변경
- [x] 진행률 관련 기능

## ☁️ ETC
 - 내용을 적어주세요
