### ISSUE TITLE
[FEAT] chatappmodule을 클라우드 서버로 이식

### ISSUE THREAD

**Issue by cjaehyuk4zed** [ajou-JSL/Backend-Multi-Module#9]
## 🖥️ Descriptions
 - chat-app-module을 클라우드 서버로 이식
 - 정상 작동이 확인 되면, main 브랜치로 한번 commit 올릴 시기가 되었다고 생각함

## ✅ Todo
- [x] develop 브랜치에, backend-module의 최신 버전과 chat-app-module의 최신 버전 합병
- [x] 최신 chat-app-module이 반영된 develop 브랜치를 클라우드 서버로 이식
- [x] 클라우드 이식 후 backend-module에 영향 없는지 테스트
- [x] 클라우드 이식 후 chat-app-module 정상 작동 테스트

## ☁️ ETC
 - 내용을 적어주세요
